### PR TITLE
updated light/dark to a component and created a toggle in css

### PR DESCRIPTION
**Pull request by RyeemZia**

### CODE REVIEW

**Review by huang-a — COMMENTED** [review]
It doesn't seem to work for me? Clicking the button toggles from light mode to dark mode, but doesn't want to do that in reverse (dark mode back to light mode). This might have to do with adding and removing the "clicked" class, but not sure.

**Comment by RyeemZia** [comment]
> It doesn't seem to work for me? Clicking the button toggles from light mode to dark mode, but doesn't want to do that in reverse (dark mode back to light mode). This might have to do with adding and removing the "clicked" class, but not sure.

Should be fixed

**Review by ErmiasMerine — APPROVED** [review]
Looks good to me

**Comment by huang-a** [comment]
@RyeemZia looks like home logo isn't working anymore. could you fix that?

**Pull request merged**
