### PR TITLE
Completed sign up and login pages

### PR DESCRIPTION
**Pull request by ErmiasMerine**

### CODE REVIEW

**Review by huang-a — DISMISSED** [review]

**Review by ErmiasMerine — COMMENTED** [review]
From my experience keeping the css for each functionality separate works better so that things don’t get confusing. In addition there seems to be test errors in features outside of the ones I implemented forcing the circleci test to fail. My changes are not responsible so it should be safe to merge

**Comment by huang-a** [comment]
Yeah, we can fix those errors later. The rationale for separate css files seems fine, it'll just be slightly more annoying to update both files.

I'm still recommending squashing some commits, so if you want to proceed as is with current commits, just ping someone else to sign off on that. Otherwise, everything looks fine to me.

**Comment by huang-a** [comment]
I'm trying to remove my change requested. I'll update this comment when I figure it out.

**Review by huang-a — CHANGES_REQUESTED** [review]
Regarding deleted comments:

**Pull request closed without merging**
